// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_headingstatusad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_headingstatusad));
        
        string IMigrationMetadata.Id
        {
            get { return "202109101329504_mig_headingstatusad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
